### ISSUE TITLE
Prettify Concurrently

### ISSUE THREAD

**Issue by wesbos** [jmsv/gatsby-plugin-prettier-build#1]
Any thoughts on doing this concurrently isntead of sync? Each one takes a few seconds, which ends up adding a few mins to my build time. 

https://github.com/jmsv/gatsby-plugin-prettier-build/blob/master/gatsby-node.js#L45

**Comment by jmsv** [comment]
Considered this! Although, the `prettier` CLI formats through files synchronously and I was worried there was a reason for this. Too many writes at the same time causing instability perhaps? Will try it out in a bit and publish a ~patch~ minor version update for you to try out :100:

**Comment by jmsv** [comment]
Published [`0.3.0`](https://www.npmjs.com/package/gatsby-plugin-prettier-build/v/0.3.0) - @wesbos does this work for you?

I'm thinking it might be worth limiting concurrency with `p-limit` or something - not sure how stable this will be with almost [1000 files](https://twitter.com/wesbos/status/1248260348685189121) to process

**Comment by wesbos** [comment]
Yeah I think limiting it to ~20 or so at once would be wise. Ill try this out shortly!

**Comment by jmsv** [comment]
@wesbos I've just added configurable concurrency limiting in `0.4.0` :+1:

**Comment by jmsv** [comment]
Looks like this works! [Deploy logs](https://app.netlify.com/sites/condescending-pasteur-8185e8/deploys/5e9883cf8660730006d0eea1) look as-expected, and checking the preview site, all `view-source`s for pages look pretty ✨

**Comment by wesbos** [comment]
:) thanks a ton for this - you are awesome
