### ISSUE TITLE
Source load's in after 2nd refresh

### ISSUE THREAD

**Issue by danielvanc** [jmsv/gatsby-plugin-prettier-build#3]
Hey there, 
After installing this plugin, running a build and going to look at view source, I'm finding that i have to refresh the page a 2nd time in order to see the actual page html load in. 

Have put the site live at: https://www.danielvanc.com/

Repo: https://github.com/danielvanc/danielvanc.com

Is this something related to the plugin or? 

Many thanks 👍

**Comment by jmsv** [comment]
Hi Daniel, I can't repro this - might be that I've misunderstood your repro steps/the problem.

If I go to your website the page loads, and if I right click some blank space (avoiding accidentally selecting text) and then click  View Source, it loads the prettified page HTML as expected at `view-source:https://www.danielvanc.com/`.

At what point are you having to do a refresh?

**Comment by jmsv** [comment]
Just occurred to me that this kind of problem could be caused by the browser cacheing old markup - have you tried clearing data for the site/hard refreshing?

**Comment by danielvanc** [comment]
Hey James,

Thanks so much for the quick reply - most appreciated 👍 

I've uploaded a [video](https://vimeo.com/412232068) of what i'm experiencing.

Notice on the first load of view source, i circle the #gatsby id and there's no page html within it. When I refresh in view source again, all the page html is then loaded in.

Prior to this, I had cleared browser cache, gatsby's cache locally and including a full rebuild from Gatsby Cloud. 

Hope the video helps...

**Comment by jmsv** [comment]
Ah I see what you mean, looks like this is due to [Gatsby's code splitting](https://www.gatsbyjs.org/docs/how-code-splitting-works/) - I think there's a way to disable it by overriding the webpack config in your `gatsby-node.js` but the site would take a performance hit so might not be worth it

**Comment by danielvanc** [comment]
Speaking to Wes B, he didn't have to do anything special for it to work ok, so must be something else with my set up. Will look into it 👍

**Comment by jmsv** [comment]
Cool, let me know if you need anything else :fire:

**Comment by danielvanc** [comment]
Hey @jmsv,
Haven looked into this further, I removed 'gatsby-plugin-offline' and now the source code seems to load first time every time. Could you try seeing if you have this problem with that plugin enabled as well?

**Comment by danielvanc** [comment]
I have managed to get it to work by adding 'cache_busting_mode' to 'gatsby-plugin-manifest'

And this 

`{
      resolve: "gatsby-plugin-offline",
      options: {
        workboxConfig: {
          globPatterns: ["**/*"],
        },
      },
    },`


I'm a little hesitant that adding `cache busting mode` to `none` is a good idea. 
However, it's noted on the very bottom of [gatsby-plugin-offline](https://www.gatsbyjs.org/packages/gatsby-plugin-offline/) to help with some caching issues.

**Comment by jmsv** [comment]
Thanks for looking into it! Are there any obvious drawbacks to using `cache_busting_mode: 'none'`? It might be worth adding some info about this to this repo's README for people with a similar setup
