### ISSUE TITLE
Doesn't seem to prettify the output

### ISSUE THREAD

**Issue by Kequc** [jmsv/gatsby-plugin-prettier-build#4]
Hello,

I've installed the plugin and added it to my plugins in gatsby but it doesn't seem to be run and the resulting html is still all on one line.

```
module.exports = {
  siteMetadata: {
    // etc...
  },
  plugins: [
    `gatsby-plugin-react-helmet`,

    // etc... <other plugins here>

    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
    'gatsby-plugin-prettier-build',
  ],
}
```

**Comment by jmsv** [comment]
hmm 🤔 do you have a link to a reproduction I could look at?

**Comment by jmsv** [comment]
closing, can't repro

feel free to open this again if an example of this problem is possible :slightly_smiling_face:
